/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BetOutcome = IDL.Record({
  'betAmount' : IDL.Nat,
  'winnings' : IDL.Nat,
  'gameName' : IDL.Text,
  'outcome' : IDL.Text,
});

export const idlService = IDL.Service({
  'createWallet' : IDL.Func([], [], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getGameHistory' : IDL.Func([], [IDL.Vec(BetOutcome)], ['query']),
  'placeBet' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'resolveBet' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'withdraw' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BetOutcome = IDL.Record({
    'betAmount' : IDL.Nat,
    'winnings' : IDL.Nat,
    'gameName' : IDL.Text,
    'outcome' : IDL.Text,
  });
  
  return IDL.Service({
    'createWallet' : IDL.Func([], [], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getGameHistory' : IDL.Func([], [IDL.Vec(BetOutcome)], ['query']),
    'placeBet' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'resolveBet' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'withdraw' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };